<a href="https://colab.research.google.com/github/sravanya-2006/space-weather-ai-guardian/blob/main/notebooks/02_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/sravanya-2006/space-weather-ai-guardian.git

Cloning into 'space-weather-ai-guardian'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 21 (delta 2), reused 11 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (21/21), 83.61 KiB | 1.64 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [2]:
%cd space-weather-ai-guardian

/content/space-weather-ai-guardian

In [3]:
import pandas as pd

df = pd.read_csv("data/raw/solar_flares.csv")

df.head()

,flrID,catalog,instruments,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,note,submissionTime,versionId,link,linkedEvents,sentNotifications
0,2024-01-01T08:33:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01T08:33Z,2024-01-01T08:54Z,2024-01-01T09:04Z,M2.3,N03E70,13536.0,NaN,2024-01-01T13:28Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
1,2024-01-01T11:54:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01T11:54Z,2024-01-01T12:25Z,2024-01-01T12:35Z,M4.7,N03E68,13536.0,NaN,2024-01-01T13:24Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
2,2024-01-02T18:02:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-02T18:02Z,2024-01-02T18:30Z,2024-01-02T18:56Z,M1.1,N05E59,13536.0,NaN,2024-01-02T19:34Z,2,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,[{'activityID': '2024-01-02T19:36:00-CME-001'}],NaN
3,2024-01-04T01:08:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04T01:08Z,2024-01-04T01:16Z,2024-01-04T01:22Z,M1.1,N02E38,13536.0,NaN,2024-01-04T01:44Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
4,2024-01-04T01:22:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04T01:22Z,2024-01-04T01:55Z,2024-01-04T02:12Z,M3.8,N04E38,13536.0,NaN,2024-01-04T03:00Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN

In [4]:
df.shape

(1128, 15)

In [5]:
import pandas as pd

df = pd.read_csv("data/raw/solar_flares.csv")

print(df.shape)
df.head()

(1128, 15)

,flrID,catalog,instruments,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,note,submissionTime,versionId,link,linkedEvents,sentNotifications
0,2024-01-01T08:33:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01T08:33Z,2024-01-01T08:54Z,2024-01-01T09:04Z,M2.3,N03E70,13536.0,NaN,2024-01-01T13:28Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
1,2024-01-01T11:54:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01T11:54Z,2024-01-01T12:25Z,2024-01-01T12:35Z,M4.7,N03E68,13536.0,NaN,2024-01-01T13:24Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
2,2024-01-02T18:02:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-02T18:02Z,2024-01-02T18:30Z,2024-01-02T18:56Z,M1.1,N05E59,13536.0,NaN,2024-01-02T19:34Z,2,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,[{'activityID': '2024-01-02T19:36:00-CME-001'}],NaN
3,2024-01-04T01:08:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04T01:08Z,2024-01-04T01:16Z,2024-01-04T01:22Z,M1.1,N02E38,13536.0,NaN,2024-01-04T01:44Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN
4,2024-01-04T01:22:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04T01:22Z,2024-01-04T01:55Z,2024-01-04T02:12Z,M3.8,N04E38,13536.0,NaN,2024-01-04T03:00Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,NaN,NaN

In [6]:
df.columns

Index(['flrID', 'catalog', 'instruments', 'beginTime', 'peakTime', 'endTime',
       'classType', 'sourceLocation', 'activeRegionNum', 'note',
       'submissionTime', 'versionId', 'link', 'linkedEvents',
       'sentNotifications'],
      dtype='object')

In [7]:
df = df.drop(
    columns=[
        "note",
        "sentNotifications",
        "link"
    ]
)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   flrID            1128 non-null   object
 1   catalog          1128 non-null   object
 2   instruments      1128 non-null   object
 3   beginTime        1128 non-null   object
 4   peakTime         1128 non-null   object
 5   endTime          1128 non-null   object
 6   classType        1128 non-null   object
 7   sourceLocation   1128 non-null   object
 8   activeRegionNum  1102 non-null   float64
 9   submissionTime   1128 non-null   object
 10  versionId        1128 non-null   int64
 11  linkedEvents     324 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 105.9+ KB

In [9]:
df["beginTime"] = pd.to_datetime(df["beginTime"])
df["peakTime"] = pd.to_datetime(df["peakTime"])
df["endTime"] = pd.to_datetime(df["endTime"])
df["submissionTime"] = pd.to_datetime(df["submissionTime"])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   flrID            1128 non-null   object
 1   catalog          1128 non-null   object
 2   instruments      1128 non-null   object
 3   beginTime        1128 non-null   datetime64[ns, UTC]
 4   peakTime         1128 non-null   datetime64[ns, UTC]
 5   endTime          1128 non-null   datetime64[ns, UTC]
 6   classType        1128 non-null   object
 7   sourceLocation   1128 non-null   object
 8   activeRegionNum  1102 non-null   float64
 9   submissionTime   1128 non-null   datetime64[ns, UTC]
 10  versionId        1128 non-null   int64
 11  linkedEvents     324 non-null    object
dtypes: datetime64[ns, UTC](4), float64(1), int64(1), object(6)
memory usage: 105.9+ KB

In [11]:
df["duration_minutes"] = (
    df["endTime"] - df["beginTime"]
).dt.total_seconds() / 60

In [12]:
df[["classType", "duration_minutes"]].head()

  classType  duration_minutes
0      M2.3              31.0
1      M4.7              41.0
2      M1.1              54.0
3      M1.1              14.0
4      M3.8              50.0

In [13]:
df["flare_class"] = df["classType"].str[0]

In [14]:
df["flare_class"].value_counts()

flare_class
M    982
C     92
X     54
Name: count, dtype: int64

In [15]:
risk_map = {
    "A": 0,
    "B": 0,
    "C": 1,
    "M": 2,
    "X": 3
}

df["risk_level"] = df["flare_class"].map(risk_map)

In [16]:
df[["classType", "flare_class", "risk_level"]].head()

  classType flare_class  risk_level
0      M2.3           M           2
1      M4.7           M           2
2      M1.1           M           2
3      M1.1           M           2
4      M3.8           M           2

In [18]:
import os

output_dir = "data/processed"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(
    os.path.join(output_dir, "solar_flares_clean.csv"),
    index=False
)

print("Clean dataset saved successfully")

Clean dataset saved successfully

In [19]:
df["flare_class"].value_counts()

flare_class
M    982
C     92
X     54
Name: count, dtype: int64

In [20]:
df["risk_level"].value_counts()

risk_level
2    982
1     92
3     54
Name: count, dtype: int64

In [21]:
df.to_csv(
    "data/processed/solar_flares_clean.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully