<a href="https://colab.research.google.com/github/sravanya-2006/space-weather-ai-guardian/blob/main/notebooks/03_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/sravanya-2006/space-weather-ai-guardian.git

Cloning into 'space-weather-ai-guardian'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 25 (delta 3), reused 11 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 90.46 KiB | 4.52 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [2]:
%cd space-weather-ai-guardian

/content/space-weather-ai-guardian

In [3]:
import pandas as pd
import numpy as np

In [8]:
!ls data/raw

solar_flares.csv

In [9]:
!ls data/processed

ls: cannot access 'data/processed': No such file or directory

In [10]:
df = pd.read_csv("data/raw/solar_flares.csv")

In [11]:
df = df.drop(
    columns=[
        "note",
        "sentNotifications",
        "link"
    ]
)

In [12]:
from google.colab import files

uploaded = files.upload()

Saving solar_flares_clean.csv to solar_flares_clean.csv

In [13]:
import pandas as pd

df = pd.read_csv("solar_flares_clean.csv")

df.head()

,flrID,catalog,instruments,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,submissionTime,versionId,linkedEvents,duration_minutes,flare_class,risk_level
0,2024-01-01T08:33:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01 08:33:00+00:00,2024-01-01 08:54:00+00:00,2024-01-01 09:04:00+00:00,M2.3,N03E70,13536.0,2024-01-01 13:28:00+00:00,1,NaN,31.0,M,2
1,2024-01-01T11:54:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01 11:54:00+00:00,2024-01-01 12:25:00+00:00,2024-01-01 12:35:00+00:00,M4.7,N03E68,13536.0,2024-01-01 13:24:00+00:00,1,NaN,41.0,M,2
2,2024-01-02T18:02:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-02 18:02:00+00:00,2024-01-02 18:30:00+00:00,2024-01-02 18:56:00+00:00,M1.1,N05E59,13536.0,2024-01-02 19:34:00+00:00,2,[{'activityID': '2024-01-02T19:36:00-CME-001'}],54.0,M,2
3,2024-01-04T01:08:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04 01:08:00+00:00,2024-01-04 01:16:00+00:00,2024-01-04 01:22:00+00:00,M1.1,N02E38,13536.0,2024-01-04 01:44:00+00:00,1,NaN,14.0,M,2
4,2024-01-04T01:22:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04 01:22:00+00:00,2024-01-04 01:55:00+00:00,2024-01-04 02:12:00+00:00,M3.8,N04E38,13536.0,2024-01-04 03:00:00+00:00,1,NaN,50.0,M,2

In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv("solar_flares_clean.csv")

df.head()

,flrID,catalog,instruments,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,submissionTime,versionId,linkedEvents,duration_minutes,flare_class,risk_level
0,2024-01-01T08:33:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01 08:33:00+00:00,2024-01-01 08:54:00+00:00,2024-01-01 09:04:00+00:00,M2.3,N03E70,13536.0,2024-01-01 13:28:00+00:00,1,NaN,31.0,M,2
1,2024-01-01T11:54:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-01 11:54:00+00:00,2024-01-01 12:25:00+00:00,2024-01-01 12:35:00+00:00,M4.7,N03E68,13536.0,2024-01-01 13:24:00+00:00,1,NaN,41.0,M,2
2,2024-01-02T18:02:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-02 18:02:00+00:00,2024-01-02 18:30:00+00:00,2024-01-02 18:56:00+00:00,M1.1,N05E59,13536.0,2024-01-02 19:34:00+00:00,2,[{'activityID': '2024-01-02T19:36:00-CME-001'}],54.0,M,2
3,2024-01-04T01:08:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04 01:08:00+00:00,2024-01-04 01:16:00+00:00,2024-01-04 01:22:00+00:00,M1.1,N02E38,13536.0,2024-01-04 01:44:00+00:00,1,NaN,14.0,M,2
4,2024-01-04T01:22:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES-P: EXIS 1.0-8.0'}],2024-01-04 01:22:00+00:00,2024-01-04 01:55:00+00:00,2024-01-04 02:12:00+00:00,M3.8,N04E38,13536.0,2024-01-04 03:00:00+00:00,1,NaN,50.0,M,2

In [15]:
df["beginTime"] = pd.to_datetime(df["beginTime"])
df["peakTime"] = pd.to_datetime(df["peakTime"])
df["endTime"] = pd.to_datetime(df["endTime"])
df["submissionTime"] = pd.to_datetime(df["submissionTime"])

In [16]:
df["hour"] = df["beginTime"].dt.hour

In [17]:
df["day"] = df["beginTime"].dt.day

In [18]:
df["month"] = df["beginTime"].dt.month

In [19]:
df["year"] = df["beginTime"].dt.year

In [20]:
df["day_of_week"] = df["beginTime"].dt.dayofweek

In [21]:
df["magnitude"] = df["classType"].str[1:].astype(float)

In [22]:
flare_map = {
    "C": 0,
    "M": 1,
    "X": 2
}

df["flare_class_encoded"] = df["flare_class"].map(flare_map)

In [23]:
df[
    [
        "classType",
        "magnitude",
        "duration_minutes",
        "hour",
        "month",
        "flare_class_encoded",
        "risk_level"
    ]
].head()

,classType,magnitude,duration_minutes,hour,month,flare_class_encoded,risk_level
0,M2.3,2.3,31.0,8,1,1,2
1,M4.7,4.7,41.0,11,1,1,2
2,M1.1,1.1,54.0,18,1,1,2
3,M1.1,1.1,14.0,1,1,1,2
4,M3.8,3.8,50.0,1,1,1,2

In [24]:
df.to_csv(
    "final_features.csv",
    index=False
)

In [27]:
from google.colab import files

files.download("final_features.csv")